---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

before_install:
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install

script:
  - yarn run test
