name: CI

on:
  push:
    branches:
      - master
  pull_request: {}
  pull_request_target: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: install dependencies
        run: yarn install
      - name: lint:js
        run: yarn lint:js
      - name: lint:hbs
        run: yarn lint:hbs
      - name: lint:css
        run: yarn lint:css

  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: install dependencies
        run: yarn install
      - name: yarn test
        run: yarn test
